;;;; src/types-structs.lisp
;;;;
;;;; Plain data: every field table here is transcribed from
;;;; KhronosGroup/Vulkan-Headers/include/vulkan/vulkan_core.h
;;;; (VK_HEADER_VERSION 360, Vulkan 1.4), not recalled from memory, using the
;;;; C type -> SB-ALIEN type mapping this system uses throughout:
;;;;   uint32_t/VkFlags/VkBool32 -> (unsigned 32)   int32_t -> (integer 32)
;;;;   uint8_t -> (unsigned 8)   uint64_t/VkDeviceSize/size_t -> (unsigned 64)
;;;;   float -> single-float     char* -> c-string
;;;; DEFINE-VK-STRUCT (macros.lisp) turns each table into the matching
;;;; SB-ALIEN struct type plus a decoder.
(in-package #:cl-vulkan-kit)

;; VkExtensionProperties (vulkan_core.h:3745-3748)
(define-vk-struct extension-properties
  ((extension-name (sb-alien:array sb-alien:char 256) (:c-string 256))
   (spec-version (sb-alien:unsigned 32))))

;; VkLayerProperties (vulkan_core.h:3750-3755)
(define-vk-struct layer-properties
  ((layer-name (sb-alien:array sb-alien:char 256) (:c-string 256))
   (spec-version (sb-alien:unsigned 32))
   (implementation-version (sb-alien:unsigned 32))
   (description (sb-alien:array sb-alien:char 256) (:c-string 256))))

;; VkApplicationInfo (vulkan_core.h:3475-3483) -- an "in" struct only, built
;; from Lisp values by CREATE-INSTANCE and never decoded back.
(define-vk-struct application-info
  ((s-type (sb-alien:integer 32))
   (p-next (* t))
   (p-application-name sb-alien:c-string)
   (application-version (sb-alien:unsigned 32))
   (p-engine-name sb-alien:c-string)
   (engine-version (sb-alien:unsigned 32))
   (api-version (sb-alien:unsigned 32)))
  :structure-type 0 ; VK_STRUCTURE_TYPE_APPLICATION_INFO
  :representation nil)

;; VkInstanceCreateInfo (vulkan_core.h:3499-3508) -- likewise "in"-only.
(define-vk-struct instance-create-info
  ((s-type (sb-alien:integer 32))
   (p-next (* t))
   (flags (sb-alien:unsigned 32))
   (p-application-info (* (sb-alien:struct application-info)))
   (enabled-layer-count (sb-alien:unsigned 32))
   (pp-enabled-layer-names (* sb-alien:c-string))
   (enabled-extension-count (sb-alien:unsigned 32))
   (pp-enabled-extension-names (* sb-alien:c-string)))
  :structure-type 1 ; VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO
  :representation nil)

;; VkExtent3D (vulkan_core.h:3404-3408)
(define-vk-struct extent-3d
  ((width (sb-alien:unsigned 32))
   (height (sb-alien:unsigned 32))
   (depth (sb-alien:unsigned 32))))

;; VkQueueFamilyProperties (vulkan_core.h:3714-3719)
(define-vk-struct queue-family-properties
  ((queue-flags (sb-alien:unsigned 32) (:bitmask queue-flags-keywords))
   (queue-count (sb-alien:unsigned 32))
   (timestamp-valid-bits (sb-alien:unsigned 32))
   (min-image-transfer-granularity (sb-alien:struct extent-3d) (:struct decode-extent-3d))))

;; VkPhysicalDeviceSparseProperties (vulkan_core.h:3694-3700)
(define-vk-struct physical-device-sparse-properties
  ((residency-standard-2d-block-shape (sb-alien:unsigned 32) :bool32)
   (residency-standard-2d-multisample-block-shape (sb-alien:unsigned 32) :bool32)
   (residency-standard-3d-block-shape (sb-alien:unsigned 32) :bool32)
   (residency-aligned-mip-size (sb-alien:unsigned 32) :bool32)
   (residency-non-resident-strict (sb-alien:unsigned 32) :bool32)))

;; VkPhysicalDeviceLimits (vulkan_core.h:3578-3685). 63 fields -- decoded to
;; a plist rather than a DEFSTRUCT so this one struct does not turn into 63
;; accessor exports for a record most callers destructure only partially.
(define-vk-struct physical-device-limits
  ((max-image-dimension-1d (sb-alien:unsigned 32))
   (max-image-dimension-2d (sb-alien:unsigned 32))
   (max-image-dimension-3d (sb-alien:unsigned 32))
   (max-image-dimension-cube (sb-alien:unsigned 32))
   (max-image-array-layers (sb-alien:unsigned 32))
   (max-texel-buffer-elements (sb-alien:unsigned 32))
   (max-uniform-buffer-range (sb-alien:unsigned 32))
   (max-storage-buffer-range (sb-alien:unsigned 32))
   (max-push-constants-size (sb-alien:unsigned 32))
   (max-memory-allocation-count (sb-alien:unsigned 32))
   (max-sampler-allocation-count (sb-alien:unsigned 32))
   (buffer-image-granularity (sb-alien:unsigned 64))
   (sparse-address-space-size (sb-alien:unsigned 64))
   (max-bound-descriptor-sets (sb-alien:unsigned 32))
   (max-per-stage-descriptor-samplers (sb-alien:unsigned 32))
   (max-per-stage-descriptor-uniform-buffers (sb-alien:unsigned 32))
   (max-per-stage-descriptor-storage-buffers (sb-alien:unsigned 32))
   (max-per-stage-descriptor-sampled-images (sb-alien:unsigned 32))
   (max-per-stage-descriptor-storage-images (sb-alien:unsigned 32))
   (max-per-stage-descriptor-input-attachments (sb-alien:unsigned 32))
   (max-per-stage-resources (sb-alien:unsigned 32))
   (max-descriptor-set-samplers (sb-alien:unsigned 32))
   (max-descriptor-set-uniform-buffers (sb-alien:unsigned 32))
   (max-descriptor-set-uniform-buffers-dynamic (sb-alien:unsigned 32))
   (max-descriptor-set-storage-buffers (sb-alien:unsigned 32))
   (max-descriptor-set-storage-buffers-dynamic (sb-alien:unsigned 32))
   (max-descriptor-set-sampled-images (sb-alien:unsigned 32))
   (max-descriptor-set-storage-images (sb-alien:unsigned 32))
   (max-descriptor-set-input-attachments (sb-alien:unsigned 32))
   (max-vertex-input-attributes (sb-alien:unsigned 32))
   (max-vertex-input-bindings (sb-alien:unsigned 32))
   (max-vertex-input-attribute-offset (sb-alien:unsigned 32))
   (max-vertex-input-binding-stride (sb-alien:unsigned 32))
   (max-vertex-output-components (sb-alien:unsigned 32))
   (max-tessellation-generation-level (sb-alien:unsigned 32))
   (max-tessellation-patch-size (sb-alien:unsigned 32))
   (max-tessellation-control-per-vertex-input-components (sb-alien:unsigned 32))
   (max-tessellation-control-per-vertex-output-components (sb-alien:unsigned 32))
   (max-tessellation-control-per-patch-output-components (sb-alien:unsigned 32))
   (max-tessellation-control-total-output-components (sb-alien:unsigned 32))
   (max-tessellation-evaluation-input-components (sb-alien:unsigned 32))
   (max-tessellation-evaluation-output-components (sb-alien:unsigned 32))
   (max-geometry-shader-invocations (sb-alien:unsigned 32))
   (max-geometry-input-components (sb-alien:unsigned 32))
   (max-geometry-output-components (sb-alien:unsigned 32))
   (max-geometry-output-vertices (sb-alien:unsigned 32))
   (max-geometry-total-output-components (sb-alien:unsigned 32))
   (max-fragment-input-components (sb-alien:unsigned 32))
   (max-fragment-output-attachments (sb-alien:unsigned 32))
   (max-fragment-dual-src-attachments (sb-alien:unsigned 32))
   (max-fragment-combined-output-resources (sb-alien:unsigned 32))
   (max-compute-shared-memory-size (sb-alien:unsigned 32))
   (max-compute-work-group-count (sb-alien:array (sb-alien:unsigned 32) 3) (:array 3))
   (max-compute-work-group-invocations (sb-alien:unsigned 32))
   (max-compute-work-group-size (sb-alien:array (sb-alien:unsigned 32) 3) (:array 3))
   (sub-pixel-precision-bits (sb-alien:unsigned 32))
   (sub-texel-precision-bits (sb-alien:unsigned 32))
   (mipmap-precision-bits (sb-alien:unsigned 32))
   (max-draw-indexed-index-value (sb-alien:unsigned 32))
   (max-draw-indirect-count (sb-alien:unsigned 32))
   (max-sampler-lod-bias sb-alien:single-float)
   (max-sampler-anisotropy sb-alien:single-float)
   (max-viewports (sb-alien:unsigned 32))
   (max-viewport-dimensions (sb-alien:array (sb-alien:unsigned 32) 2) (:array 2))
   (viewport-bounds-range (sb-alien:array sb-alien:single-float 2) (:array 2))
   (viewport-sub-pixel-bits (sb-alien:unsigned 32))
   (min-memory-map-alignment (sb-alien:unsigned 64))
   (min-texel-buffer-offset-alignment (sb-alien:unsigned 64))
   (min-uniform-buffer-offset-alignment (sb-alien:unsigned 64))
   (min-storage-buffer-offset-alignment (sb-alien:unsigned 64))
   (min-texel-offset (sb-alien:integer 32))
   (max-texel-offset (sb-alien:unsigned 32))
   (min-texel-gather-offset (sb-alien:integer 32))
   (max-texel-gather-offset (sb-alien:unsigned 32))
   (min-interpolation-offset sb-alien:single-float)
   (max-interpolation-offset sb-alien:single-float)
   (sub-pixel-interpolation-offset-bits (sb-alien:unsigned 32))
   (max-framebuffer-width (sb-alien:unsigned 32))
   (max-framebuffer-height (sb-alien:unsigned 32))
   (max-framebuffer-layers (sb-alien:unsigned 32))
   (framebuffer-color-sample-counts (sb-alien:unsigned 32))
   (framebuffer-depth-sample-counts (sb-alien:unsigned 32))
   (framebuffer-stencil-sample-counts (sb-alien:unsigned 32))
   (framebuffer-no-attachments-sample-counts (sb-alien:unsigned 32))
   (max-color-attachments (sb-alien:unsigned 32))
   (sampled-image-color-sample-counts (sb-alien:unsigned 32))
   (sampled-image-integer-sample-counts (sb-alien:unsigned 32))
   (sampled-image-depth-sample-counts (sb-alien:unsigned 32))
   (sampled-image-stencil-sample-counts (sb-alien:unsigned 32))
   (storage-image-sample-counts (sb-alien:unsigned 32))
   (max-sample-mask-words (sb-alien:unsigned 32))
   (timestamp-compute-and-graphics (sb-alien:unsigned 32) :bool32)
   (timestamp-period sb-alien:single-float)
   (max-clip-distances (sb-alien:unsigned 32))
   (max-cull-distances (sb-alien:unsigned 32))
   (max-combined-clip-and-cull-distances (sb-alien:unsigned 32))
   (discrete-queue-priorities (sb-alien:unsigned 32))
   (point-size-range (sb-alien:array sb-alien:single-float 2) (:array 2))
   (line-width-range (sb-alien:array sb-alien:single-float 2) (:array 2))
   (point-size-granularity sb-alien:single-float)
   (line-width-granularity sb-alien:single-float)
   (strict-lines (sb-alien:unsigned 32) :bool32)
   (standard-sample-locations (sb-alien:unsigned 32) :bool32)
   (optimal-buffer-copy-offset-alignment (sb-alien:unsigned 64))
   (optimal-buffer-copy-row-pitch-alignment (sb-alien:unsigned 64))
   (non-coherent-atom-size (sb-alien:unsigned 64)))
  :representation :plist)

;; VkPhysicalDeviceProperties (vulkan_core.h:3702-3712)
(define-vk-struct physical-device-properties
  ((api-version (sb-alien:unsigned 32))
   (driver-version (sb-alien:unsigned 32))
   (vendor-id (sb-alien:unsigned 32))
   (device-id (sb-alien:unsigned 32))
   (device-type (sb-alien:integer 32) (:enum physical-device-type-keyword))
   (device-name (sb-alien:array sb-alien:char 256) (:c-string 256))
   (pipeline-cache-uuid (sb-alien:array (sb-alien:unsigned 8) 16) (:array 16))
   (limits (sb-alien:struct physical-device-limits) (:struct decode-physical-device-limits))
   (sparse-properties (sb-alien:struct physical-device-sparse-properties)
    (:struct decode-physical-device-sparse-properties))))
